/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on May 14, 2012, 11:23:33 AM
 */
package it.uniroma1.dis.wsngroup.graphic;

import it.uniroma1.dis.wsngroup.parsing.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo Bergamini
 */
public class Main extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        parsingType = new javax.swing.ButtonGroup();
        format = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        realTime = new javax.swing.JRadioButton();
        offline = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        json = new javax.swing.JRadioButton();
        adList = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        dnf = new javax.swing.JRadioButton();
        gexf = new javax.swing.JRadioButton();
        netlogo = new javax.swing.JRadioButton();
        adMatrix = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        filename = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        virtualYes = new javax.swing.JRadioButton();
        virtualNo = new javax.swing.JRadioButton();
        dynamicGexf = new javax.swing.JRadioButton();
        aggregateGexf = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        useDB = new javax.swing.JRadioButton();
        notUseDB = new javax.swing.JRadioButton();
        startTSLabel = new javax.swing.JLabel();
        endTSLabel = new javax.swing.JLabel();
        startTSField = new javax.swing.JTextField();
        endTSField = new javax.swing.JTextField();

        fileChooser.setCurrentDirectory(new java.io.File("/home/lorenzo/workspace/SocioPatterns"));
        fileChooser.setDialogTitle("This is my open dialog");
        fileChooser.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SocialDIS Parser");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SocialDIS Parsing Tools"));

        jLabel1.setText("Welcome to SocialDIS Parser. Follow the instructions  to start parsing files");

        nextButton.setText("Next --->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parsing Type"));

        parsingType.add(realTime);
        realTime.setText("Real Time");
        realTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realTimeActionPerformed(evt);
            }
        });

        parsingType.add(offline);
        offline.setSelected(true);
        offline.setText("Off-line");
        offline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offlineActionPerformed(evt);
            }
        });

        jLabel2.setText("Please select between Real Time or Off-line Parsing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(realTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(offline)
                        .addGap(88, 88, 88))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realTime)
                    .addComponent(offline))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Format"));

        format.add(json);
        json.setText("Json");
        json.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsonActionPerformed(evt);
            }
        });

        format.add(adList);
        adList.setSelected(true);
        adList.setText("Adjacency List");
        adList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adListActionPerformed(evt);
            }
        });

        jLabel3.setText("Please select the desired output format");

        format.add(dnf);
        dnf.setText("DNF");
        dnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnfActionPerformed(evt);
            }
        });

        format.add(gexf);
        gexf.setText("GEXF");
        gexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gexfActionPerformed(evt);
            }
        });

        format.add(netlogo);
        netlogo.setText("Netlogo");
        netlogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netlogoActionPerformed(evt);
            }
        });

        format.add(adMatrix);
        adMatrix.setText("Adjacency Matrix");
        adMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adMatrixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(json)
                            .addComponent(adList)
                            .addComponent(adMatrix))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(netlogo)
                            .addComponent(dnf)
                            .addComponent(gexf))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(json)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adMatrix))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gexf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dnf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(netlogo)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("File Details"));

        jLabel5.setText("Please select the position of the file to parse");

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        filename.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Options (depending on the format)"));
        jPanel5.setEnabled(false);

        jLabel4.setText("Create virtual links");
        jLabel4.setEnabled(false);

        jLabel7.setText("GEXF Options");
        jLabel7.setEnabled(false);

        buttonGroup3.add(virtualYes);
        virtualYes.setText("YES");
        virtualYes.setEnabled(false);

        buttonGroup3.add(virtualNo);
        virtualNo.setText("NO");
        virtualNo.setEnabled(false);
        virtualNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virtualNoActionPerformed(evt);
            }
        });

        buttonGroup4.add(dynamicGexf);
        dynamicGexf.setText("Dynamic GEXF");
        dynamicGexf.setEnabled(false);
        dynamicGexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dynamicGexfActionPerformed(evt);
            }
        });

        buttonGroup4.add(aggregateGexf);
        aggregateGexf.setText("Aggregate GEXF");
        aggregateGexf.setEnabled(false);
        aggregateGexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggregateGexfActionPerformed(evt);
            }
        });

        jLabel8.setText("JSON Option: Use DB?");
        jLabel8.setEnabled(false);

        buttonGroup5.add(useDB);
        useDB.setText("YES");
        useDB.setEnabled(false);

        buttonGroup5.add(notUseDB);
        notUseDB.setText("NO");
        notUseDB.setEnabled(false);
        notUseDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notUseDBActionPerformed(evt);
            }
        });

        startTSLabel.setText("Start TimeStamp");

        endTSLabel.setText("End TimeStamp");

        startTSField.setText("0");
        startTSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTSFieldActionPerformed(evt);
            }
        });

        endTSField.setText("0");
        endTSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTSFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(startTSLabel)
                    .addComponent(endTSLabel))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTSField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(virtualYes)
                            .addComponent(aggregateGexf)
                            .addComponent(useDB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notUseDB)
                            .addComponent(dynamicGexf)
                            .addComponent(virtualNo)))
                    .addComponent(startTSField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(virtualYes)
                    .addComponent(virtualNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dynamicGexf)
                    .addComponent(aggregateGexf)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(useDB)
                    .addComponent(notUseDB))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTSLabel)
                    .addComponent(startTSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTSLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 959, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        String[] values = new String[5];
        int startTS = 0;
        int endTS = 0;
        for (int i = 0; i < values.length; i++) {
            values[i] = "";
        }

        if (filename.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error! Please indicate a valid file to parse!");
        } else {
            /*
            values[0] = Type of Parsing (RealTime or Offline)
            values[1] = Desired Output Format
            values[2] = If Output Format != Adjacency*, then indicates if we want virtual links or not; else it is NULL
            values[3] = If Output Format = GEXF indicates if we want dynamic or aggregate file, else 
            if Output Format = JSON it indicates if we want to use the DB, else it is NULL
            
            
             */

            if (realTime.isSelected()) {
                values[0] = "RealTime";
            } else {
                values[0] = "Offline";
            }

            if (adList.isSelected()) {
                values[1] = "Adjacency List";
                //AVVIA PARSING E TERMINA QUI
            } else if (adMatrix.isSelected()) {
                values[1] = "Adjacency Matrix";
                //AVVIA PARSING E TERMINA QUI
            } else if (netlogo.isSelected()) {
                values[1] = "Netlogo";
                if (virtualYes.isSelected()) {
                    values[2] = "YES";
                    //AVVIA PARSING E TERMINA QUI
                } else {
                    values[2] = "NO";
                    //AVVIA PARSING
                }
            } else if (dnf.isSelected()) {
                values[1] = "Dynamic Network Format";
                if (virtualYes.isSelected()) {
                    values[2] = "YES";
                    //AVVIA PARSING E TERMINA QUI
                } else {
                    values[2] = "NO";
                    //AVVIA PARSING
                }
            } else if (json.isSelected()) {
                values[1] = "Json";
                if (virtualYes.isSelected()) {
                    values[2] = "YES";
                    //AVVIA PARSING E TERMINA QUI
                } else {
                    values[2] = "NO";
                    //AVVIA PARSING
                }
                if (useDB.isSelected()) {
                    values[3] = "UseDB";
                } else {
                    values[3] = "NotUseDB";
                }
            } else if (gexf.isSelected()) {
                values[1] = "Gexf";
                if (virtualYes.isSelected()) {
                    values[2] = "YES";
                    //AVVIA PARSING E TERMINA QUI
                } else {
                    values[2] = "NO";
                    //AVVIA PARSING
                }
                if (aggregateGexf.isSelected()) {
                    values[3] = "Aggregate";
                } else {
                    values[3] = "Dynamic";
                }
            }
            
            startTS = Integer.parseInt(startTSField.getText());
            endTS = Integer.parseInt(endTSField.getText());

            if (realTime.isSelected()) {
                try {
                    GraphicRealTimeParser.initRealTimeParsing(values, filename.getText());
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                GraphicLogParser.initParsing(values, filename.getText(), startTS, endTS);
            }

        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            filename.setText(file.getAbsolutePath());

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void virtualNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virtualNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_virtualNoActionPerformed

    private void jsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsonActionPerformed
        jPanel5.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(true);
        virtualNo.setEnabled(true);
        virtualNo.setSelected(true);
        jLabel8.setEnabled(true);
        useDB.setEnabled(true);
        notUseDB.setEnabled(true);
        notUseDB.setSelected(true);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);

    }//GEN-LAST:event_jsonActionPerformed

    private void dynamicGexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dynamicGexfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dynamicGexfActionPerformed

    private void aggregateGexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggregateGexfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggregateGexfActionPerformed

    private void notUseDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notUseDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notUseDBActionPerformed

    private void gexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gexfActionPerformed
        jPanel5.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel7.setEnabled(true);
        virtualYes.setEnabled(true);
        virtualNo.setEnabled(true);
        virtualNo.setSelected(true);
        dynamicGexf.setEnabled(true);
        aggregateGexf.setEnabled(true);
        dynamicGexf.setSelected(true);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);


    }//GEN-LAST:event_gexfActionPerformed

    private void dnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnfActionPerformed
        jPanel5.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(true);
        virtualNo.setEnabled(true);
        virtualNo.setSelected(true);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);

    }//GEN-LAST:event_dnfActionPerformed

    private void netlogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netlogoActionPerformed
        jPanel5.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(true);
        virtualNo.setEnabled(true);
        virtualNo.setSelected(true);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);

    }//GEN-LAST:event_netlogoActionPerformed

    private void adMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adMatrixActionPerformed
        jPanel5.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(false);
        virtualNo.setEnabled(false);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);
    }//GEN-LAST:event_adMatrixActionPerformed

    private void adListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adListActionPerformed
        jPanel5.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(false);
        virtualNo.setEnabled(false);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);
    }//GEN-LAST:event_adListActionPerformed

    private void realTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realTimeActionPerformed
        jPanel5.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(false);
        virtualNo.setEnabled(false);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);
        adList.setEnabled(false);
        adMatrix.setEnabled(false);
        netlogo.setEnabled(false);
        virtualYes.setEnabled(false);
        useDB.setEnabled(false);
        dnf.setEnabled(false);
        gexf.setEnabled(false);
        json.setEnabled(false);
        aggregateGexf.setEnabled(false);
        startTSLabel.setEnabled(false);
        endTSLabel.setEnabled(false);
        startTSField.setEnabled(false);
        endTSField.setEnabled(false);
    }//GEN-LAST:event_realTimeActionPerformed

    private void offlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlineActionPerformed
        jPanel5.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel7.setEnabled(false);
        virtualYes.setEnabled(false);
        virtualNo.setEnabled(false);
        dynamicGexf.setEnabled(false);
        aggregateGexf.setEnabled(false);
        jLabel8.setEnabled(false);
        useDB.setEnabled(false);
        notUseDB.setEnabled(false);
        adList.setEnabled(true);
        adMatrix.setEnabled(true);
        netlogo.setEnabled(true);
        virtualYes.setEnabled(false);
        useDB.setEnabled(false);
        dnf.setEnabled(true);
        gexf.setEnabled(true);
        json.setEnabled(true);
        startTSLabel.setEnabled(true);
        endTSLabel.setEnabled(true);
        startTSField.setEnabled(true);
        endTSField.setEnabled(true);
        aggregateGexf.setEnabled(false);    }//GEN-LAST:event_offlineActionPerformed

    private void endTSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTSFieldActionPerformed

    private void startTSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTSFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adList;
    private javax.swing.JRadioButton adMatrix;
    private javax.swing.JRadioButton aggregateGexf;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton dnf;
    private javax.swing.JRadioButton dynamicGexf;
    private javax.swing.JTextField endTSField;
    private javax.swing.JLabel endTSLabel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField filename;
    private javax.swing.ButtonGroup format;
    private javax.swing.JRadioButton gexf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton json;
    private javax.swing.JRadioButton netlogo;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton notUseDB;
    private javax.swing.JRadioButton offline;
    private javax.swing.ButtonGroup parsingType;
    private javax.swing.JRadioButton realTime;
    private javax.swing.JTextField startTSField;
    private javax.swing.JLabel startTSLabel;
    private javax.swing.JRadioButton useDB;
    private javax.swing.JRadioButton virtualNo;
    private javax.swing.JRadioButton virtualYes;
    // End of variables declaration//GEN-END:variables
}
